baseURL: /
languageCode: en-us
title: Hugo ButterCMS starter
module:
  mounts:
    - source: content
      target: content
    - source: data
      target: data
    - source: remote/data
      target: data
    - source: remote/content
      target: content
