[build]
  command = "go run github.com/ButterCMS/hugo-starter-buttercms/prebuild && hugo"

[build.environment]
  GO_VERSION = "1.22.2"
  HUGO_VERSION = "0.147.0"
  HUGO_ENV = "production"

[template.environment]
BUTTERCMS_API_TOKEN = "BUTTERCMS_API_TOKEN: Paste your ButterCMS secret token here"
BUTTERCMS_PREVIEW = "BUTTERCMS_PREVIEW: Set this value to `true` to show draft content and `false` to hide"

[template.build]
  command = "go run github.com/ButterCMS/hugo-starter-buttercms/prebuild && hugo"
