[build]
  command = "go run github.com/ButterCMS/hugo-starter-buttercms/prebuild && hugo"

[build.environment]
  GO_VERSION = "1.18"

[template.environment]
BUTTERCMS_API_TOKEN = "Paste Your ButterCMS Secret Token Here"
BUTTERCMS_PREVIEW = "Set to `true` to show draft content and `false` to hide"

[template.build]
  command = "go run github.com/ButterCMS/hugo-starter-buttercms/prebuild && hugo"
