[build]
  command = "go run github.com/ButterCMS/hugo-starter-buttercms/prebuild && hugo"

[build.environment]
  GO_VERSION = "1.18"

[template.environment]
BUTTERCMS_API_TOKEN = "Your_ButterCMS_secret_token_here"
BUTTERCMS_PREVIEW = false

[template.build]
  command = "go run github.com/ButterCMS/hugo-starter-buttercms/prebuild && hugo"
