name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Fetch Remote data
        run: go run github.com/ButterCMS/hugo-starter-buttercms/prebuild
        env:
          BUTTERCMS_API_TOKEN: ${{ secrets.BUTTERCMS_API_TOKEN }}

      - uses: int128/update-generated-files-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


      # - name: Build
      #   run: hugo

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   # if: ${{ github.ref == 'refs/heads/main' }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public

