name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true 
          fetch-depth: 0   

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Fetch Remote data
        run: go run github.com/ButterCMS/hugo-starter-buttercms/prebuild
        env:
          BUTTERCMS_API_TOKEN: ${{ secrets.BUTTERCMS_API_TOKEN }}

      - uses: EndBug/add-and-commit@v9 
        with:
          add: 'remote'
          message: 'Fetch remote data'
