name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'

      - name: Fetch Remote data
        run: go run github.com/ButterCMS/hugo-starter-buttercms/prebuild
        env:
          BUTTERCMS_API_TOKEN: ${{ secrets.BUTTERCMS_API_TOKEN }}

      - name: Build
        run: hugo

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   # if: ${{ github.ref == 'refs/heads/main' }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ github.event.head_commit.message }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
